#!/usr/bin/env python3
"""
Turn a 1 bit BMP into a C++ source/header pair holding its pixels.

The output is a packed bitmap in .rodata, one bit per pixel, rows top to
bottom and within a row the leftmost pixel in the most significant bit - the
layout pika::lcd::ST75160::bitmap() draws. A 160x100 logo is 2000 bytes.

    tools/bmp2cpp.py images/pika_logo.bmp --name pika_logo \
        --out-dir src/pika/lcd/images --namespace pika::lcd

Only uncompressed 1 bit BMPs are read, which is what any editor's
"monochrome bitmap" export produces; anything deeper is an error rather than
a guess at a threshold. Which of the two palette colours becomes an ink bit is
decided by the palette itself - the darker entry wins - so a file drawn black
on white and the same file with its colours swapped both come out the right
way round. --invert overrides that for a panel image meant to read as
negative.

Standard library only, no numpy.
"""

from __future__ import annotations

import argparse
import hashlib
import struct
import sys
from pathlib import Path

BYTES_PER_LINE = 12


def parse_bmp(data: bytes) -> tuple[int, int, list[bytearray]]:
    """
    Decode a 1 bit BMP into rows of raw bits, top row first.

    Returns the width, the height and one bytearray per row, still in the
    file's own bit sense: a set bit is palette index 1.
    """
    if data[:2] != b"BM":
        raise SystemExit("not a BMP: the file does not start with 'BM'")
    if len(data) < 54:
        raise SystemExit("truncated BMP: no room for a BITMAPINFOHEADER")

    pixel_offset = struct.unpack_from("<I", data, 10)[0]
    header_size, width, height, planes, bpp, compression = struct.unpack_from("<IiiHHI", data, 14)

    if header_size < 40:
        raise SystemExit(f"unsupported BMP: {header_size} byte header, only BITMAPINFOHEADER and later are read")
    if planes != 1 or bpp != 1:
        raise SystemExit(f"unsupported BMP: {bpp} bits per pixel, this reads 1 bit files only")
    if compression != 0:
        raise SystemExit(f"unsupported BMP: compression {compression}, only uncompressed (BI_RGB) is read")
    if width <= 0:
        raise SystemExit(f"unsupported BMP: width {width}")

    # A negative height means the rows are already stored top to bottom.
    top_down = height < 0
    height = abs(height)

    # Rows are padded out to a multiple of four bytes, which is not the stride
    # the output uses.
    src_stride = ((width + 31) // 32) * 4
    if pixel_offset + src_stride * height > len(data):
        raise SystemExit("truncated BMP: the pixel data is shorter than the header claims")

    rows = []
    for y in range(height):
        src_y = y if top_down else height - 1 - y
        start = pixel_offset + src_y * src_stride
        rows.append(bytearray(data[start : start + src_stride]))

    return width, height, rows


def ink_is_index_one(data: bytes) -> bool:
    """
    Whether a set bit in the file means ink, judged by the palette.

    The two entries are BGRA; the darker one is the ink. Equal luminance -
    which a missing or degenerate palette gives - falls back to the usual
    convention of 0 being black.
    """
    header_size = struct.unpack_from("<I", data, 14)[0]
    palette = 14 + header_size

    if palette + 8 > len(data):
        return False

    def luma(off: int) -> int:
        b, g, r = data[off], data[off + 1], data[off + 2]
        return 2 * r + 5 * g + b

    return luma(palette + 4) < luma(palette)


def pack(width: int, height: int, rows: list[bytearray], invert: bool) -> bytes:
    """Repack the rows to the output stride, with ink as a set bit."""
    stride = (width + 7) // 8
    out = bytearray()

    for row in rows:
        packed = bytearray(row[:stride])
        packed += bytes(stride - len(packed))
        if invert:
            packed = bytearray(b ^ 0xFF for b in packed)

        # Bits past the right edge sit in the last byte of every row. They are
        # never drawn, but a zero there keeps the hex readable.
        if width % 8:
            packed[-1] &= (0xFF << (8 - width % 8)) & 0xFF

        out += packed

    return bytes(out)


def format_array(blob: bytes, stride: int) -> str:
    """One line per BYTES_PER_LINE bytes, never running two rows together."""
    lines = []
    for start in range(0, len(blob), stride):
        row = blob[start : start + stride]
        for chunk_start in range(0, len(row), BYTES_PER_LINE):
            chunk = row[chunk_start : chunk_start + BYTES_PER_LINE]
            lines.append("    " + ",".join(f"0x{b:02x}" for b in chunk) + ",")
    return "\n".join(lines)


def banner(src: Path, digest: str, args, width: int, height: int, size: int) -> str:
    return f"""/*
 * Generated by tools/bmp2cpp.py - do not edit.
 *
 *   source     {src.name} ({digest[:16]})
 *   image      {width}x{height}, 1 bit per pixel, {size} bytes
 *
 * Regenerate with:
 *   tools/bmp2cpp.py {src} --name {args.name} \\
 *       --out-dir {args.out_dir} --namespace {args.namespace}
 */"""


def emit(args, src: Path, digest: str, width: int, height: int, blob: bytes) -> None:
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    stride = (width + 7) // 8
    head = banner(src, digest, args, width, height, len(blob))
    ns_open = f"namespace {args.namespace} {{" if args.namespace else ""
    ns_close = f"}}// namespace {args.namespace}" if args.namespace else ""

    header = f"""{head}

#pragma once

#include <cstddef>
#include <cstdint>

{ns_open}

/** @brief  Image width in pixels. */
constexpr int {args.name}_width = {width};

/** @brief  Image height in pixels. */
constexpr int {args.name}_height = {height};

/** @brief  Bytes per row: one bit per pixel, rounded up. */
constexpr size_t {args.name}_stride = {stride};

/** @brief  Packed 1bpp pixels in flash, top row first, MSB leftmost. */
extern const uint8_t {args.name}[{args.name}_stride * {args.name}_height];

{ns_close}
"""

    # The definition has to say extern too: a const at namespace scope has
    # internal linkage in C++ by default, and the header's declaration would
    # then find nothing to bind to at link time.
    source = f"""{head}

#include "{args.name}.h"

{ns_open}

extern const uint8_t {args.name}[{args.name}_stride * {args.name}_height] = {{
{format_array(blob, stride)}
}};

{ns_close}
"""

    (out_dir / f"{args.name}.h").write_text(header)
    (out_dir / f"{args.name}.cpp").write_text(source)


def main() -> int:
    p = argparse.ArgumentParser(description="Embed a 1 bit BMP as a packed C++ bitmap.")
    p.add_argument("bmp", type=Path, help="input file: an uncompressed 1 bit BMP")
    p.add_argument("--name", help="C++ identifier for the array (default: the file stem)")
    p.add_argument("--out-dir", default=".", help="directory to write <name>.h and <name>.cpp into")
    p.add_argument("--namespace", default="", help="C++ namespace to wrap the data in")
    p.add_argument("--invert", action="store_true", help="swap ink and background")
    args = p.parse_args()

    if not args.bmp.is_file():
        raise SystemExit(f"{args.bmp}: no such file")
    if args.name is None:
        args.name = args.bmp.stem.replace("-", "_").replace(" ", "_")
    if not args.name.isidentifier():
        raise SystemExit(f"{args.name!r} is not a usable C++ identifier")

    data = args.bmp.read_bytes()
    digest = hashlib.sha256(data).hexdigest()

    width, height, rows = parse_bmp(data)
    # The file needs flipping when a set bit is not already ink, and --invert
    # flips that answer again.
    invert = ink_is_index_one(data) == args.invert

    blob = pack(width, height, rows, invert)

    emit(args, args.bmp, digest, width, height, blob)

    print(f"{args.name}: {width}x{height}, {len(blob)} bytes -> {args.out_dir}/{args.name}.{{h,cpp}}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
