SET(CMAKE_SYSTEM_NAME Generic)
SET(CMAKE_SYSTEM_PROCESSOR arm)

set(TOOLCHAIN_TARGET_TRIPLET "arm-none-eabi")
set(CMAKE_CROSSCOMPILING ON)

SET(CMAKE_FIND_ROOT_PATH "${TOOLCHAIN_PREFIX}/${TOOLCHAIN_TARGET_TRIPLET}" ${EXTRA_FIND_PATH})
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

include(${PROJECT_ROOT}/cmake/toolchain-tools.cmake)
SELECT_TOOLCHAIN()
